from enum import Enum

class RobotStates(Enum):
    IDLE = "IDLE"
    SCANNING_POSE = "SCANNING_POSE"
    SCANNING_FOR_PURPLE_BOXES = "SCANNING_FOR_PURPLE_BOXES"
    VERIFYING_POSE = "VERIFYING_POSE"
    VERIFYING_PURPLE_BOX = "VERIFYING_PURPLE_BOX"
    GET_FUEL_TANK_COORDS = "GET_FUEL_TANK_COORDS"
    PICKUP_POSE = "PICKUP_POSE"
    CLOSE_JAW = "CLOSE_JAW"
    PRE_STORAGE_POSE = "PRE_STORAGE_POSE"
    STORAGE_POSE = "STORAGE_POSE"
    RELEASE_JAW = "RELEASE_JAW"