from enum import Enum

class BoardObjects(Enum):
    SMALL_PACKAGE = "SMALL_PACKAGE"
    BIG_PACKAGE = "BIG_PACKAGE"
    FUEL_TANK = "FUEL_TANK"
    THRUSTER = "THRUSTER"
    SMALL_PACKAGE_GRABBER = "SMALL_PACKAGE_GRABBER"
    FUEL_TANK_GRABBER = "FUEL_TANK_GRABBER"