from enum import Enum

class Poses(Enum):
    SET_BULK_GRABBER_ARMS = "SET_BULK_GRABBER_ARMS"
    CLOSE_TOP_BULK_GRABBER_ARM = "CLOSE_TOP_BULK_GRABBER_ARM"
    RAISE_BULK_GRABBER = "RAISE_BULK_GRABBER"
    SCAN = "SCAN"
    VERIFY = "VERIFY"
    FRONT = "FRONT"
    SMALL_PACKAGE_SCAN = "SMALL_PACKAGE_SCAN"
    DROP_OFF_SMALL_PACKAGES = "DROP_OFF_SMALL_PACKAGES"
    RELEASE_SMALL_PACKAGES = "RELEASE_SMALL_PACKAGES"
    FUEL_TANK_SCAN = "FUEL_TANK_SCAN"


    